"""add ip address

Revision ID: a3d9449248fb
Revises: 7d5ef2b960bc
Create Date: 2024-02-27 15:19:46.578925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d9449248fb'
down_revision = '7d5ef2b960bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipaddress', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_info', schema=None) as batch_op:
        batch_op.drop_column('ipaddress')

    # ### end Alembic commands ###
